### ISSUE TITLE
Bug: Theming - Lists are not properly displayed with certain browsers

### ISSUE THREAD

**Issue by drozas** [P2Pvalue/cbpp-directory-code#61]
@pdavenne, @cataspanglish,

While adding subgroups for the new form (see #42 ), the fields which are displayed as lists are not properly displayed (see screenshot). I have tried with the default Drupal theme, and this works fine. Therefore, this is an issue related to the theme created by the external company. Could you please let them know, so they create a new version. Thanks!

Test scenario:
- Logged in as an authenticated user (either test account our using masquerade)
- Create a new community: http://directory.p2pvalue.eu/node/add/cbpp-community

![list_theming_bug](https://cloud.githubusercontent.com/assets/1962473/7350954/2ee559a6-ecfa-11e4-9c01-66b22024d888.png)

**Comment by pdavenne** [comment]
I can see the lists nicely in Opera and Chrome, maybe it's a Firefox issue? (I'm not considering here the use of IE, for obvious reasons).

**Comment by drozas** [comment]
Hi @pdavenne !
It is also happening to me under Chrome (Version 41.0.2272.76 Ubuntu 14.10 (64-bit)).
This is something the developers of the theme could take a look at, as part of the new version of the theme related to #54

**Comment by pdavenne** [comment]
I can see it well on Chrome 42.0.2311.135 Windows 8.1, going to try it under Ubuntu now.

**Comment by lifesized** [comment]
Ok, so did we change the theme at all since we installed it?

I can send them the latest version and ask for the changes to be made.

**Comment by drozas** [comment]
Hi @lifesized !
Nope, there were not any changes in the custom theme at all (https://github.com/P2Pvalue/cbpp-directory-code/tree/master/sites/all/themes), although I updated the parent theme they used (adaptive). They should still have commit permissions in the code repository. Let me know if you need a dump of the DB (and private files at sites/default/files) for them to work with locally. Thanks! ;-)

**Comment by lifesized** [comment]
Ok, that's perfect then, they can just d/l the latest version from here and fix the issues. 
So we are basically asking for browser compatibility. I will contact them to see if they do such a thing.

**Comment by lifesized** [comment]
I found it would cost $500 to fix compatibility issues. Is the problem severe enough @drozas that you think we should do this still?

**Comment by drozas** [comment]
Hi @lifesized ,

This is a critical issue, which is causing some end users not to be able to contribute. Hence, I would recommend to fix it.

**Comment by lifesized** [comment]
Hi David,

Thanks for the insights.
I will pay to fix the issues.

Can you refer me to the correct url for the latest version of the directory
so they fix the right thing?

J

On Tue, Jun 9, 2015 at 11:24 AM, David Rozas <notifications@github.com>
wrote:

> Hi @lifesized <https://github.com/lifesized> ,
>
> This is a critical issue, which is causing some end users not to be able
> to contribute. Hence, I would recommend to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/P2Pvalue/cbpp-directory-code/issues/61#issuecomment-110290104>
> .
>



-- 

James Burke

T:+31 (0)6 5244 6445

Twitter: https://twitter.com/lifesized
LinkedIn: nl.linkedin.com/in/lifesized

   -

**Comment by drozas** [comment]
Hello James,

The production site is: http://directory.p2pvalue.eu/
The source code can be found at: https://github.com/P2Pvalue/cbpp-directory-code
I will send you a dump of the DB now via e-mail, so they can test it locally. 
For the deployment, I will send you the credentials of the server at Autónoma de Barcelona via e-mail as well (or I can do it myself after they commit the code, and if they create some documentation with any required steps regarding site-building/modules configuration).

**Comment by drozas** [comment]
The proposed design by @lifesized  for the changes in the UX related to this, can be found at #66 (see picture attached by James).

**Comment by drozas** [comment]
Changes implemented by Sparx successfully tested at dev site: http://norefresh.thesparxitsolutions.com/drupal/CSS4572/node/add/cbpp-community

**Comment by drozas** [comment]
TO-DO: contact P2PF and UAB to ask for green light on changes

**Comment by drozas** [comment]
Dear all,

The changes to the form to add new cases related to the design created by James and implemented by Sparx are already available at a development site at http://norefresh.thesparxitsolutions.com/drupal/CSS4572/

I have been testing them myself with several browsers under Linux and with a virtual machine under Windows, and everything looks perfectly. If you have time to test them under other Operating Systems / Browsers it would be great. In order to do so, you would need to:

​Login at http://norefresh.thesparxitsolutions.com/drupal/CSS4572/user/login
User: **********
Pass: **********
Go to http://norefresh.thesparxitsolutions.com/drupal/CSS4572/node/add/cbpp-community to inspect the form. If you want to create a testing case, please remember to uncheck the option "Announce this post on Twitter". Otherwise, a tweet will be automatically created at the @P2Pvalue account
If we are happy with the theming/design changes, I will give green light to Sparx and proceed to deploy them to the main site. I will them announce the new version of the directory in the main list.

Finally, one more minor issue (#57). The contents at the about page (http://directory.p2pvalue.eu/about) are a duplication of the ones at the home (http://directory.p2pvalue.eu/). I would suggest either to update one of them, or remove the about temporarily if not (since this is actually penalized in SEO terms).

Best,

David

**Comment by drozas** [comment]
Successfully deployed and tested at production site
