### ISSUE TITLE
UX: review of the form to add/edit CBPP cases

### ISSUE THREAD

**Issue by drozas** [P2Pvalue/cbpp-directory-code#66]
Requirements gathered with Marco and James during the P2Pvalue Paris meeting

- Review the UX and design of the adding CBPP case to improve the usability (@james)

**Comment by drozas** [comment]
Hi @cataspanglish! I assign this to you, although it will be done by James (just to keep track of the tasks).

**Comment by lifesized** [comment]
1) Remove the list arrow elements from the first half of the form 

2) Widen the drop down so it's no so squashed. Try doubling the width so titles have room to breathe 
![create_cbpp_community___cbpp_directory__beta_ 2](https://cloud.githubusercontent.com/assets/594539/7937184/c237bb30-093e-11e5-809c-181d57ccf959.png)

3) Increase the font size of "Add more information" so you establish as more important in the hierarchy of the other form elements. Currently it feels like a hidden feature
![create_cbpp_community___cbpp_directory__beta_](https://cloud.githubusercontent.com/assets/594539/7937094/198dac38-093e-11e5-8d44-413b361e8a24.png)

**Comment by drozas** [comment]
Changes implemented by Sparx successfully tested at dev site: http://norefresh.thesparxitsolutions.com/drupal/CSS4572/node/add/cbpp-community

**Comment by drozas** [comment]
TO-DO: contact P2PF and UAB to ask for green light on changes

**Comment by drozas** [comment]
Dear all,

The changes to the form to add new cases related to the design created by James and implemented by Sparx are already available at a development site at http://norefresh.thesparxitsolutions.com/drupal/CSS4572/

I have been testing them myself with several browsers under Linux and with a virtual machine under Windows, and everything looks perfectly. If you have time to test them under other Operating Systems / Browsers it would be great. In order to do so, you would need to:

​Login at http://norefresh.thesparxitsolutions.com/drupal/CSS4572/user/login
User: **********
Pass: **********
Go to http://norefresh.thesparxitsolutions.com/drupal/CSS4572/node/add/cbpp-community to inspect the form. If you want to create a testing case, please remember to uncheck the option "Announce this post on Twitter". Otherwise, a tweet will be automatically created at the @P2Pvalue account
If we are happy with the theming/design changes, I will give green light to Sparx and proceed to deploy them to the main site. I will them announce the new version of the directory in the main list.

Finally, one more minor issue (https://github.com/P2Pvalue/cbpp-directory-code/issues/57). The contents at the about page (http://directory.p2pvalue.eu/about) are a duplication of the ones at the home (http://directory.p2pvalue.eu/). I would suggest either to update one of them, or remove the about temporarily if not (since this is actually penalized in SEO terms).

Best,

David

**Comment by drozas** [comment]
Successfully deployed and tested at production site
