### ISSUE TITLE
Adding leaflet map

### ISSUE THREAD

**Issue by calbasi** [P2Pvalue/cbpp-directory-code#75]

**Comment by calbasi** [comment]
Target: [http://directori.p2pvalue.eu/](url)

**Comment by calbasi** [comment]
Modules to install and enable:

- Geofield (present at this moment, disabled; then, enabled)
- geoPHP (present at this moment, disabled; then, enabled)
- geocoder 1.x (1.2 version present at this moment, disabled; then updated to 1.3 version and enabled)
- https://www.drupal.org/project/leaflet (you should install his library too). Leaflet views should be enabled too.
- https://www.drupal.org/project/leaflet_markercluster (you should install his library too)

Howto steps:

1. We should crate a geofield field at CBPP Communities content type, to store coordinates from postal address field (using geocoder widget).

2. We should create a leaflet type View, with exposed filters.

3. Update all community type nodes to geocode some of them, which have postal address field data set. We could use Views Bulk Operation module.

**Comment by calbasi** [comment]
We created 2 Views: a block view to display at home page and a Page View with a filter block feature to display as section (Visualise)

**Comment by drozas** [comment]
Hi @calbasi , I have added leaflet and leaflet_markercluster in the libraries (copy them from the production server) ;-)
